name: KHB Live Tests
on:
  push:
    paths:
      - 'KHB_LIVE_DO_NOT_UPDATE!!!!!!.postman_collection.json'
      - 'KHBLIVE.postman_environment.json'
      - '.github/workflows/khb-tests.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'   # كل يوم الساعة 10 صباحًا بتوقيت الأردن
jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g newman newman-reporter-htmlextra
      - run: newman run "KHB_LIVE_DO_NOT_UPDATE!!!!!!.postman_collection.json" -e KHBLIVE.postman_environment.json --reporters "cli,htmlextra" --reporter-htmlextra-export joborders-report.html
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: joborders-report
          path: joborders-report.html
      - name: Send Email Report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: qatest@nafith.com
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "JOBORDERS-Live - ${{ github.run_id }}"
          to: haljassem@nafith.com, skhalayleh@nafith.com
          from: qatest@nafith.com
          body: "JO borders daily health test (Live): ${{ job.status }}"
          attachments: joborders-report.html
